# Generated by Django 4.0.5 on 2022-06-30 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('rut', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=80, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('contraseña', models.CharField(max_length=80, verbose_name='Contraseña')),
                ('imagen', models.ImageField(blank=True, default='sinfoto.jpg', null=True, upload_to='images/', verbose_name='Imagen')),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripción')),
                ('precio', models.CharField(max_length=80, verbose_name='Precio')),
                ('descuentosub', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descuento subscriptor')),
                ('descuentoferta', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descuento por oferta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de bodega')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('cantidad', models.CharField(max_length=80, verbose_name='Cantidad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
