# Generated by Django 4.0.5 on 2022-07-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrado_producto_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edituser',
            fields=[
                ('id', models.CharField(max_length=6, verbose_name='Id de')),
                ('tipo_usuario', models.CharField(max_length=40, verbose_name='Tipo de usuario')),
                ('rut', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('sub', models.CharField(max_length=80, null=True, verbose_name='Con subscripción')),
                ('contraseña', models.CharField(max_length=80, verbose_name='Contraseña')),
                ('imagen', models.ImageField(blank=True, default='sinfoto.jpg', null=True, upload_to='images/', verbose_name='Imagen')),
            ],
        ),
    ]
