# Generated by Django 4.0.5 on 2022-07-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_edituser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edituser',
            name='id',
            field=models.CharField(max_length=6, verbose_name='Id de usuario'),
        ),
    ]
