# Generated by Django 4.0.5 on 2022-07-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_delete_registrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='sinfoto.jpg', null=True, upload_to='images/', verbose_name='Imagen'),
        ),
    ]
