# Generated by Django 4.0.5 on 2022-07-08 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_cantidad_delete_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Estado')),
                ('nombreEstado', models.CharField(max_length=80, verbose_name='Tipo de estado')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('Nro_factura', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('nombre_cliente', models.CharField(max_length=80, verbose_name='Nombre')),
                ('monto_total', models.CharField(max_length=80, verbose_name='Monto total')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estado')),
            ],
        ),
        migrations.DeleteModel(
            name='Edituser',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, default='sinfoto.jpg', null=True, upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de usuario'),
        ),
    ]
