# Generated by Django 4.0.5 on 2022-07-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estado_factura_delete_edituser_perfilusuario_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sub',
            field=models.BooleanField(blank=True, null=True, verbose_name='Deseoo recibir'),
        ),
    ]
