# Generated by Django 4.0.5 on 2022-07-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfilusuario_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='sub',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
