# Generated by Django 4.0.5 on 2022-07-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_perfilusuario_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tipo de usuario')),
                ('nombreTipo', models.CharField(max_length=80, verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo_usuario'),
        ),
    ]
