# Generated by Django 4.0.5 on 2022-07-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tipo_usuario_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='sub',
            field=models.BooleanField(blank=True, null=True, verbose_name='Subscripcion'),
        ),
    ]
