# Generated by Django 4.0.5 on 2022-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_perfilusuario_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id de usuario'),
        ),
    ]
