# Generated by Django 4.0.5 on 2022-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_perfilusuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='sub',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
