# Generated by Django 4.0.5 on 2022-07-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_perfilusuario_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sub',
            field=models.BooleanField(blank=True, null=True, verbose_name='sub'),
        ),
    ]
